name: android-studio
adopt-info: android-studio
summary: The IDE for Android
description: |
  Android Studio provides the fastest tools for building apps on every type
  of Android device.

  World-class code editing, debugging, performance tooling, a flexible build
  system, and an instant build/deploy system all allow you to focus on
  building unique and high quality apps.

grade: stable
confinement: classic
base: core20
compression: lzo
architectures:
  - build-on: amd64

apps:
  android-studio:
    command: android-studio/bin/studio.sh
    environment:
      PULSE_SERVER: $XDG_RUNTIME_DIR/pulse/native

parts:
  android-studio:
    plugin: nil
    source: .
    override-build: |
      snapcraftctl build
      echo "Get latest release..."
      RELEASE_INFO=$(python3 -u get_latest.py)
      DOWNLOAD_URL=$(echo ${RELEASE_INFO} | cut -d ' ' -f2)

      wget --quiet "${DOWNLOAD_URL}" -O "${SNAPCRAFT_PART_INSTALL}/android-studio.tar.gz"
      tar -xf "${SNAPCRAFT_PART_INSTALL}/android-studio.tar.gz" -C "${SNAPCRAFT_PART_INSTALL}"

      # Cleanup
      rm "${SNAPCRAFT_PART_INSTALL}/android-studio.tar.gz"

      # Set version
      snapcraftctl set-version $(echo $RELEASE_INFO | cut -d ' ' -f1)
    build-packages:
      - wget
      - python3
    build-attributes:
      - no-patchelf
